### ISSUE TITLE
Panic during BenchmarkReadHashMapWithWritesUint test

### ISSUE THREAD

**Issue by No-ops** [cornelk/hashmap#8]
It seems to occur with low frequency but I managed to trigger it multiple times. 

```
go.exe test -v github.com/cornelk/hashmap -bench ^BenchmarkReadHashMapWithWritesUint$ -run ^$

panic: runtime error: invalid memory address or nil pointer dereference

[signal 0xc0000005 code=0x0 addr=0x0 pc=0x50a758]

goroutine 9 [running]:

github.com/cornelk/hashmap.BenchmarkReadHashMapWithWritesUint.func2(0xc04208c020)

	.../Go/src/github.com/cornelk/hashmap/benchmark_test.go:124 +0x78

testing.(*B).RunParallel.func1(0xc042398070, 0xc042398068, 0xc042398060, 0xc0420b2160, 0xc042002260)

	C:/Go/src/testing/benchmark.go:605 +0xc9

created by testing.(*B).RunParallel

	C:/Go/src/testing/benchmark.go:606 +0x1b6
exit status 2
FAIL	github.com/cornelk/hashmap	0.242s
```

Tested on windows 10 x64.

**Comment by kplachkov** [comment]
This issue is not present in the latest commit.
